modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/ItsBlackGear/Offlimits/issues"

[[mods]]
   modId="offlimits"
   version="${version}"
   displayName="offlimits"
   logoFile="icon.png"
   authors="ItsBlackGear"
   description="Expand the world building limits!"

[[dependencies.offlimits]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.offlimits]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,)"
   ordering="NONE"
   side="BOTH"
